# Generated by Django 5.0.4 on 2024-04-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=10)),
                ('quantity', models.IntegerField(default=0)),
                ('when_needed', models.DateTimeField()),
                ('contact_number', models.IntegerField(max_length=11)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
    ]
